SET search_path TO auth;

ALTER TABLE users DROP CONSTRAINT chk_role;
ALTER TABLE users ADD CONSTRAINT chk_role
    CHECK (role IN ('USER','LAB_MANAGER','ADMIN','PROJECT_MANAGER','TECHNICIAN','CLIENT'));

ALTER TABLE users ADD COLUMN IF NOT EXISTS client_id UUID;
